### ISSUE TITLE
Under what license this code is distributed?

### ISSUE THREAD

**Issue by eclipseo** [benesch/cgosymbolizer#1]
This package is a dependency of CockroachDB but no licensing information is provided. As such it makes it difficult for distro integrator to package it.
Please provide a LICENSE file for this repo.

**Comment by benesch** [comment]
Are you packaging CockroachDB for Fedora, out of curiosity?

@bdarnell if I understand the PIIA correctly I believe Cockroach Labs owns the copyright here. Ok to license under Apache 2.0?

**Comment by eclipseo** [comment]
Yes, we are rebuilding our whole Go stack in Fedora and CockroachDB is part of new dependencies we need to package.

**Comment by bdarnell** [comment]
> if I understand the PIIA correctly I believe Cockroach Labs owns the copyright here

Correct (thanks for remembering this!) 

> Ok to license under Apache 2.0?

Yes, you can license this under either Apache 2.0 or BSD (as used in https://github.com/ianlancetaylor/cgosymbolizer/blob/master/LICENSE, which might make it easier to unify the two packages at some point)

**Comment by benesch** [comment]
Great, thanks, @bdarnell! Good point about using the BSD 3-clause to match ianlancetaylor's package.

@eclipseo, this should be good to go. Thanks for the report.

**Comment by eclipseo** [comment]
Thanks!
